module.exports = {
  VOTES_TO_BAN: 2,
  VOTES_TO_UNBAN: 4,
  VOTES_FOR_DAY: 0.5,
  VOTES_FOR_RESTART: 0.75,
  MAX_PLAYERS: 100,
  UPDATE_TIMER: 60000,
  USING_ESSENTIALS: true,
  RESTART_TIMER: 86400000,
  CACHE_TIMER: 1000,
  ONLINE_POINT_MINS: 1,
  LOGFILE: '../../MasonJar.log',
  SERVER_JAR: '/jars/spigot_server.jar',
  DEFAULT_OP: 'That_8Bit_Trip'
};
